# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sdas-app"
client_id = "9abefbad0013e21170f063acd1af0f2c"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "sdas-app.myshopify.com"
